// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ToFSO2VEbUwkeLI_9vDxQZOzwih-Z6E',
    appId: '1:12920504952:web:2821b3696879f9346ba38d',
    messagingSenderId: '12920504952',
    projectId: 'agri-connect-36d65',
    authDomain: 'agri-connect-36d65.firebaseapp.com',
    databaseURL: 'https://agri-connect-36d65-default-rtdb.firebaseio.com',
    storageBucket: 'agri-connect-36d65.firebasestorage.app',
    measurementId: 'G-XYHEN02MT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQxqmubKBevyoFMm9drJ1BC6Dl-lntgjk',
    appId: '1:12920504952:android:4ada2e24fa8144946ba38d',
    messagingSenderId: '12920504952',
    projectId: 'agri-connect-36d65',
    databaseURL: 'https://agri-connect-36d65-default-rtdb.firebaseio.com',
    storageBucket: 'agri-connect-36d65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHC08H6ZnvEWd4QsSvXjkmFuVK9g2lkq8',
    appId: '1:12920504952:ios:f1562fa24c8c41556ba38d',
    messagingSenderId: '12920504952',
    projectId: 'agri-connect-36d65',
    databaseURL: 'https://agri-connect-36d65-default-rtdb.firebaseio.com',
    storageBucket: 'agri-connect-36d65.firebasestorage.app',
    iosBundleId: 'com.example.agriConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHC08H6ZnvEWd4QsSvXjkmFuVK9g2lkq8',
    appId: '1:12920504952:ios:f1562fa24c8c41556ba38d',
    messagingSenderId: '12920504952',
    projectId: 'agri-connect-36d65',
    databaseURL: 'https://agri-connect-36d65-default-rtdb.firebaseio.com',
    storageBucket: 'agri-connect-36d65.firebasestorage.app',
    iosBundleId: 'com.example.agriConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6ToFSO2VEbUwkeLI_9vDxQZOzwih-Z6E',
    appId: '1:12920504952:web:e62cdbec807f5a8a6ba38d',
    messagingSenderId: '12920504952',
    projectId: 'agri-connect-36d65',
    authDomain: 'agri-connect-36d65.firebaseapp.com',
    databaseURL: 'https://agri-connect-36d65-default-rtdb.firebaseio.com',
    storageBucket: 'agri-connect-36d65.firebasestorage.app',
    measurementId: 'G-2260JF901Z',
  );
}
